---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rails6-pg
  labels:
    app: rails6
    component: pg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
