---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rails6-redis
  labels:
    app: rails6
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
