---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rails6-uploads
  labels:
    app: rails6
    component: uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
