development:
  adapter: redis
  url: <%= ENV['REDISTOGO_URL'] || ENV.fetch('REDIS_URL') { 'redis://localhost:6379/' } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDISTOGO_URL'] || ENV.fetch('REDIS_URL') { 'redis://localhost:6379/' } %>
  channel_prefix: rails6_production
