---
apiVersion: v1
kind: Service
metadata:
  name: rails6-pg
  labels:
    app: rails6
    component: pg
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    app: rails6
    component: pg
