---
apiVersion: v1
kind: Service
metadata:
  name: rails6-puma
  labels:
    app: rails6
    component: puma
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
  selector:
    app: rails6
    component: puma
