---
apiVersion: v1
kind: Service
metadata:
  name: rails6-redis
  labels:
    app: rails6
    component: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    app: rails6
    component: redis
